version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 626052500009.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=626052500009.dkr.ecr.ap-south-1.amazonaws.com/ecs-hybrid-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Build started
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Creating imagedefinitions.json
      - printf '[{"name":"ecs-hybridapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json